"""Initial migration with all tables

Revision ID: 3d4d4f13ff35
Revises:
Create Date: 2026-01-10 21:45:09.852885

"""

from typing import Sequence, Union

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d4d4f13ff35"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Users table (Independent)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("social_provider", sa.String(length=50), nullable=False),
        sa.Column("social_id", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("social_id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    # 2. LLM Providers (Independent)
    op.create_table(
        "llm_providers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("auth_type", sa.Text(), nullable=False),
        sa.Column("doc_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # 3. Workflows (Depends on Users, Apps - but Apps depends on Workflows)
    # Circular dependency Apps <-> Workflows resolved by creating Workflows first without FK to Apps,
    # then creating Apps with FK to Workflows, then adding FK to Workflows for Apps.
    # WAIT - Workflows has 'app_id' NOT NULL. So Apps must exist first.
    # BUT Apps has 'workflow_id' (nullable).
    # So: Create Apps (without workflow_id FK) -> Create Workflows -> Add FK to Apps.

    # Let's try: Users -> Apps (no FK to Workflow) -> Workflows -> ... -> Add FK to Apps

    op.create_table(
        "apps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("workflow_id", sa.UUID(), nullable=True),
        sa.Column("active_deployment_id", sa.UUID(), nullable=True),
        sa.Column("url_slug", sa.String(), nullable=False),
        sa.Column("auth_secret", sa.String(), nullable=False),
        sa.Column("is_api_enabled", sa.Boolean(), nullable=False),
        sa.Column("api_req_per_minute", sa.Integer(), nullable=False),
        sa.Column("api_req_per_hour", sa.Integer(), nullable=False),
        sa.Column("is_market", sa.Boolean(), nullable=False),
        sa.Column(
            "forked_from",
            sa.UUID(),
            nullable=True,
            comment="Original app ID if cloned from marketplace",
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        # DEFERRED: sa.ForeignKeyConstraint(["workflow_id"],["workflows.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url_slug"),
    )
    op.create_index(op.f("ix_apps_created_by"), "apps", ["created_by"], unique=False)
    op.create_index(op.f("ix_apps_id"), "apps", ["id"], unique=False)
    op.create_index(op.f("ix_apps_is_market"), "apps", ["is_market"], unique=False)

    op.create_table(
        "workflows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("graph", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "env_variables", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "runtime_variables", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["apps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workflows_app_id"), "workflows", ["app_id"], unique=False)
    op.create_index(
        op.f("ix_workflows_created_by"), "workflows", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_workflows_id"), "workflows", ["id"], unique=False)
    op.create_table(
        "connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("database", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("encrypted_password", sa.Text(), nullable=False),
        sa.Column("use_ssh", sa.Boolean(), nullable=False),
        sa.Column("ssh_host", sa.String(), nullable=True),
        sa.Column("ssh_port", sa.Integer(), nullable=True),
        sa.Column("ssh_username", sa.String(), nullable=True),
        sa.Column("ssh_auth_type", sa.String(), nullable=True),
        sa.Column("encrypted_ssh_password", sa.Text(), nullable=True),
        sa.Column("encrypted_ssh_private_key", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "knowledge_bases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("embedding_model", sa.String(length=50), nullable=False),
        sa.Column("top_k", sa.Integer(), nullable=False),
        sa.Column("similarity_threshold", sa.Float(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "llm_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("credential_name", sa.Text(), nullable=False),
        sa.Column("encrypted_config", sa.Text(), nullable=False),
        sa.Column("config_preview", sa.Text(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("quota_type", sa.Text(), nullable=False),
        sa.Column("quota_limit", sa.BigInteger(), nullable=False),
        sa.Column("quota_used", sa.BigInteger(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["llm_providers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_llm_credentials_user_id"), "llm_credentials", ["user_id"], unique=False
    )
    op.create_table(
        "llm_models",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("model_id_for_api_call", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("context_window", sa.Integer(), nullable=False),
        sa.Column("input_price_1k", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("output_price_1k", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["llm_providers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workflow_deployments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "API", "WEBAPP", "WIDGET", "MCP", "WORKFLOW_NODE", name="deploymenttype"
            ),
            nullable=False,
        ),
        sa.Column(
            "graph_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "input_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="StartNode 입력 변수 스키마",
        ),
        sa.Column(
            "output_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="AnswerNode 출력 변수 스키마",
        ),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["apps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_deployments_app_id"),
        "workflow_deployments",
        ["app_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_deployments_id"), "workflow_deployments", ["id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("knowledge_base_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum("FILE", "API", "DB", name="sourcetype"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("chunk_size", sa.Integer(), nullable=False),
        sa.Column("chunk_overlap", sa.Integer(), nullable=False),
        sa.Column("meta_info", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding_model", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "llm_rel_credential_models",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("credential_id", sa.UUID(), nullable=False),
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_id"], ["llm_credentials.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["model_id"], ["llm_models.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("deployment_id", sa.UUID(), nullable=False),
        sa.Column(
            "node_id", sa.String(), nullable=False, comment="ScheduleTrigger 노드 ID"
        ),
        sa.Column(
            "cron_expression",
            sa.String(),
            nullable=False,
            comment="Cron 표현식 (예: '0 9 * * *' = 매일 오전 9시)",
        ),
        sa.Column(
            "timezone",
            sa.String(),
            nullable=False,
            comment="타임존 (예: Asia/Seoul, UTC)",
        ),
        sa.Column(
            "last_run_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="마지막 실행 시간",
        ),
        sa.Column(
            "next_run_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="다음 실행 예정 시간 (APScheduler가 계산)",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["workflow_deployments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_schedules_deployment_id"), "schedules", ["deployment_id"], unique=True
    )
    op.create_index(op.f("ix_schedules_id"), "schedules", ["id"], unique=False)
    op.create_index(
        op.f("ix_schedules_next_run_at"), "schedules", ["next_run_at"], unique=False
    )
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("deployment_id", sa.UUID(), nullable=True),
        sa.Column("workflow_version", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "SUCCESS", "FAILED", "STOPPED", name="runstatus"),
            nullable=False,
        ),
        sa.Column(
            "trigger_mode",
            sa.Enum("MANUAL", "API", name="runtriggermode"),
            nullable=False,
        ),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("outputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("meta_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("total_cost", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["workflow_deployments.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_runs_deployment_id"),
        "workflow_runs",
        ["deployment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_runs_status"), "workflow_runs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_runs_user_id"), "workflow_runs", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_runs_workflow_id"),
        "workflow_runs",
        ["workflow_id"],
        unique=False,
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("knowledge_base_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "llm_usage_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("credential_id", sa.UUID(), nullable=False),
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=True),
        sa.Column("workflow_run_id", sa.UUID(), nullable=True),
        sa.Column("node_id", sa.Text(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_id"], ["llm_credentials.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["model_id"], ["llm_models.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"], ["workflow_runs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_llm_usage_logs_credential_id"),
        "llm_usage_logs",
        ["credential_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_llm_usage_logs_model_id"), "llm_usage_logs", ["model_id"], unique=False
    )
    op.create_index(
        op.f("ix_llm_usage_logs_user_id"), "llm_usage_logs", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_llm_usage_logs_workflow_id"),
        "llm_usage_logs",
        ["workflow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_llm_usage_logs_workflow_run_id"),
        "llm_usage_logs",
        ["workflow_run_id"],
        unique=False,
    )
    op.create_table(
        "workflow_node_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_run_id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("node_type", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "SUCCESS", "FAILED", "SKIPPED", name="noderunstatus"),
            nullable=False,
        ),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "process_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("outputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_node_runs_workflow_run_id"),
        "workflow_node_runs",
        ["workflow_run_id"],
        unique=False,
    )

    # ADD DEFERRED FOREIGN KEYS
    op.create_foreign_key(
        "fk_apps_workflow_id_workflows", "apps", "workflows", ["workflow_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workflow_node_runs_workflow_run_id"), table_name="workflow_node_runs"
    )
    op.drop_table("workflow_node_runs")
    op.drop_index(
        op.f("ix_llm_usage_logs_workflow_run_id"), table_name="llm_usage_logs"
    )
    op.drop_index(op.f("ix_llm_usage_logs_workflow_id"), table_name="llm_usage_logs")
    op.drop_index(op.f("ix_llm_usage_logs_user_id"), table_name="llm_usage_logs")
    op.drop_index(op.f("ix_llm_usage_logs_model_id"), table_name="llm_usage_logs")
    op.drop_index(op.f("ix_llm_usage_logs_credential_id"), table_name="llm_usage_logs")
    op.drop_table("llm_usage_logs")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_workflow_runs_workflow_id"), table_name="workflow_runs")
    op.drop_index(op.f("ix_workflow_runs_user_id"), table_name="workflow_runs")
    op.drop_index(op.f("ix_workflow_runs_status"), table_name="workflow_runs")
    op.drop_index(op.f("ix_workflow_runs_deployment_id"), table_name="workflow_runs")
    op.drop_table("workflow_runs")
    op.drop_index(op.f("ix_schedules_next_run_at"), table_name="schedules")
    op.drop_index(op.f("ix_schedules_id"), table_name="schedules")
    op.drop_index(op.f("ix_schedules_deployment_id"), table_name="schedules")
    op.drop_table("schedules")
    op.drop_table("llm_rel_credential_models")
    op.drop_table("documents")
    op.drop_index(op.f("ix_workflow_deployments_id"), table_name="workflow_deployments")
    op.drop_index(
        op.f("ix_workflow_deployments_app_id"), table_name="workflow_deployments"
    )
    op.drop_table("workflow_deployments")
    op.drop_table("llm_models")
    op.drop_index(op.f("ix_llm_credentials_user_id"), table_name="llm_credentials")
    op.drop_table("llm_credentials")
    op.drop_table("knowledge_bases")
    op.drop_table("connections")
    op.drop_index(op.f("ix_workflows_id"), table_name="workflows")
    op.drop_index(op.f("ix_workflows_created_by"), table_name="workflows")
    op.drop_index(op.f("ix_workflows_app_id"), table_name="workflows")
    op.drop_table("workflows")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("llm_providers")
    op.drop_index(op.f("ix_apps_is_market"), table_name="apps")
    op.drop_index(op.f("ix_apps_id"), table_name="apps")
    op.drop_index(op.f("ix_apps_created_by"), table_name="apps")
    op.drop_table("apps")
    # ### end Alembic commands ###
